### PR TITLE
Change to new C++ based addon interface style

### PR DESCRIPTION
**Pull request by AlwinEsch**
This are changes related to Kodi request https://github.com/xbmc/xbmc/pull/12262

**Note:** Build on Windows not testet!

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Also changed the settings.xml here.

**Comment by asavah** [comment]
gcc doesn't like this:
```
visualization.spectrum/src/opengl_spectrum.cpp:158:12: error: returning a value from a constructor
     return ADDON_STATUS_UNKNOWN;
            ^~~~~~~~~~~~~~~~~~~~
visualization.spectrum/src/opengl_spectrum.cpp:163:12: error: returning a value from a constructor
     return ADDON_STATUS_UNKNOWN;
```

**Comment by AlwinEsch** [comment]
.Sorry I bring a fix. Not using here OpenGL ES 2.0 and had overlooked it

**Comment by asavah** [comment]
@AlwinEsch Don't worry, that was just to let you and notspiff about the error.
What you are doing is HUGE and I guess that some glitches are to be expected.
Keep up your awesome work.

**Pull request merged**
